import Navbar from "@/components/common/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "@/components/common/Footer";
import TopNav from "@/components/common/TopNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <div className="flex min-h-screen flex-col justify-between">
        <div>
          <TopNav />
          <div className="sticky top-0 z-50">
            <Navbar />
          </div>
          <main>{children}</main>
          <Footer />
        </div>
      </div>
    </html>
  );
}
